### PR TITLE
update metric Otel conversion

### PR DESCRIPTION
**Pull request by narcis96**

### CODE REVIEW

**Comment by narcis96** [comment]
> you also need to update the examples on README file, right?

done

**Comment by heitorganzeli** [comment]
now it looks like code wasn't changed... did you merge those other changes already?

also, if you put namespace on resource, are you creating new resource objects if you get different namespaces from the metrics?

**Comment by narcis96** [comment]
> now it looks like code wasn't changed... did you merge those other changes already?
> 
> also, if you put namespace on resource, are you creating new resource objects if you get different namespaces from the metrics?

there was a git issue. fixed now.

**Review by heitorganzeli — APPROVED** [review]
great work

**Pull request merged**
