### PR TITLE
rename region_name to region_id and simplify CesClient interface

### PR DESCRIPTION
**Pull request by narcis96**

### CODE REVIEW

**Comment by heitorganzeli** [comment]
any reason for this change? i actually prefer ces receiver, because it's the name of the service and there are other services for metrics in huawei.

but, i'm fine if you want to change

**Comment by narcis96** [comment]
> any reason for this change? i actually prefer ces receiver, because it's the name of the service and there are other services for metrics in huawei.
> 
> but, i'm fine if you want to change

The  reason for using the more generic name 'metrics' instead of 'ces' is to provide flexibility in the future. If we decide to replace CES with another service, the transition will be smoother without requiring additional changes to the receiver name. Additionally, the service name is clearly documented in the README, ensuring that there's no confusion about what which service is used.

**Comment by heitorganzeli** [comment]
> > any reason for this change? i actually prefer ces receiver, because it's the name of the service and there are other services for metrics in huawei.
> > but, i'm fine if you want to change
> 
> The reason for using the more generic name 'metrics' instead of 'ces' is to provide flexibility in the future. If we decide to replace CES with another service, the transition will be smoother without requiring additional changes to the receiver name. Additionally, the service name is clearly documented in the README, ensuring that there's no confusion about what which service is used.

hmm, in my o mind, CES wouldn't be replaced, since it's a established service. But, we would expand the number of huawei components to support other services, like AOM or APM. which also export metrics... but it's separate from CES

**Comment by narcis96** [comment]
> > > any reason for this change? i actually prefer ces receiver, because it's the name of the service and there are other services for metrics in huawei.
> > > but, i'm fine if you want to change
> > 
> > 
> > The reason for using the more generic name 'metrics' instead of 'ces' is to provide flexibility in the future. If we decide to replace CES with another service, the transition will be smoother without requiring additional changes to the receiver name. Additionally, the service name is clearly documented in the README, ensuring that there's no confusion about what which service is used.
> 
> hmm, in my o mind, CES wouldn't be replaced, since it's a established service. But, we would expand the number of huawei components to support other services, like AOM or APM. which also export metrics... but it's separate from CES

got it. then we will keep the name of the receiver as it is. 

PTAL : this PR has been re-branded to something a bit different.

**Review by heitorganzeli — APPROVED** [review]

**Pull request merged**
